<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'

type Barrier = { label:string; visible_evidence:string; affected_users:string[]; urgency:'low'|'medium'|'high'; confidence:number; box_2d:number[]|null; immediate_guidance:string; low_cost_action:string; structural_action:string }
type Audit = { summary:string; status:'likely_accessible'|'needs_review'|'potential_barrier'|'no_barrier_visible'|'insufficient_evidence'|'immediate_safety_concern'; overall_confidence:number; barriers:Barrier[]; cannot_confirm:string[]; visitor_guidance:string; manager_actions:string[]; report_text:string; evidence_quality?:'low'|'medium'|'high'; requested_photos?:string[]; requires_review?:boolean; consistency_warning?:string }
type SavedAudit = { id:number; createdAt:string; location:string; summary:string; status:Audit['status']; result:Audit; preview?:string }

const file=ref<File|null>(null),preview=ref(''),previewData=ref(''),placeType=ref('campus'),perspective=ref('general'),description=ref(''),location=ref(''),owner=ref('Facilities'),state=ref<'idle'|'analyzing'|'success'|'error'>('idle'),error=ref(''),result=ref<Audit|null>(null),activeTab=ref('visitor'),expanded=ref<number|null>(0),history=ref<SavedAudit[]>(JSON.parse(localStorage.getItem('barrier2action-history')||'[]')),dark=ref(localStorage.getItem('barrier2action-theme')==='dark'),input=ref<HTMLInputElement|null>(null),toolbarOpen=ref(false),readingFont=ref(localStorage.getItem('b2a-reading-font')||'default'),textScale=ref(Number(localStorage.getItem('b2a-text-scale')||'1')),highContrast=ref(localStorage.getItem('b2a-high-contrast')==='true'),reduceMotion=ref(localStorage.getItem('b2a-reduce-motion')==='true'),isReading=ref(false)
const statusLabel=computed(()=>result.value?.status==='potential_barrier'?'Potential barrier':result.value?.status==='insufficient_evidence'?'Potential barrier — closer evidence required':result.value?.status==='needs_review'?'Needs review':'No barrier visible in this view')
const caseId=ref(''), complaintRef=ref(localStorage.getItem('barrier2action-complaint-ref')||''), complaintStatus=ref(localStorage.getItem('barrier2action-complaint-status')||'Not submitted')
const actionRoute=computed(()=>placeType.value==='campus'||placeType.value==='office'?{name:'Facilities / venue manager',url:''}:placeType.value==='transit'?{name:'Sugamya Bharat',url:'https://sugamyabharat.gov.in/'}:{name:'CPGRAMS',url:'https://pgportal.gov.in/'})
const statusClass=computed(()=>result.value?.status||'')
const highCount=computed(()=>result.value?.barriers.filter(b=>b.urgency==='high').length||0)
const affectedCount=computed(()=>new Set(result.value?.barriers.flatMap(b=>b.affected_users)||[]).size)
function toggleTheme(){dark.value=!dark.value;localStorage.setItem('barrier2action-theme',dark.value?'dark':'light');document.documentElement.classList.toggle('theme-dark',dark.value)}
function setReadingFont(value:string){readingFont.value=value;localStorage.setItem('b2a-reading-font',value)}
function setScale(value:number){textScale.value=value;localStorage.setItem('b2a-text-scale',String(value))}
function toggleContrast(){highContrast.value=!highContrast.value;localStorage.setItem('b2a-high-contrast',String(highContrast.value))}
function toggleMotion(){reduceMotion.value=!reduceMotion.value;localStorage.setItem('b2a-reduce-motion',String(reduceMotion.value))}
function readReport(){if(!result.value||isReading.value)return;window.speechSynthesis?.cancel();const speech=new SpeechSynthesisUtterance(result.value.report_text);speech.onend=()=>{isReading.value=false;syncSpeechControls()};speech.onerror=()=>{isReading.value=false;syncSpeechControls()};isReading.value=true;syncSpeechControls();window.speechSynthesis?.speak(speech)}
function stopReading(){window.speechSynthesis?.cancel();isReading.value=false;syncSpeechControls()}
function syncSpeechControls(){const update=(button:HTMLButtonElement,read:boolean)=>{button.disabled=!result.value||(read&&isReading.value);button.title=!result.value?'Analyze a space first':read&&isReading.value?'Reading report…':read?'Read the report aloud':'Stop reading';button.classList.toggle('reading-active',read&&isReading.value);button.classList.toggle('stop-active',!read&&isReading.value)};document.querySelectorAll<HTMLButtonElement>('.toolbar-actions button').forEach((button,index)=>update(button,index===0));document.querySelectorAll<HTMLButtonElement>('.speech-report-controls button').forEach((button,index)=>update(button,index===0));const report=document.querySelector('.report');const container=report?.parentElement;if(container&&!container.querySelector('.speech-report-controls')){const controls=document.createElement('div');controls.className='speech-report-controls';const read=document.createElement('button');read.textContent='▶ Read report aloud';const stop=document.createElement('button');stop.textContent='■ Stop reading';read.onclick=readReport;stop.onclick=stopReading;controls.append(read,stop);container.append(controls)}}
onMounted(()=>{const observer=new MutationObserver(syncSpeechControls);observer.observe(document.body,{childList:true,subtree:true});syncSpeechControls()})
function chooseFile(e:Event){const f=(e.target as HTMLInputElement).files?.[0];if(!f)return;if(!['image/jpeg','image/png','image/webp','image/avif'].includes(f.type)){error.value='Use a JPG, PNG, WebP, or AVIF image.';state.value='error';return}file.value=f;preview.value=URL.createObjectURL(f);const reader=new FileReader();reader.onload=()=>{previewData.value=String(reader.result||'')};reader.readAsDataURL(f);error.value='';result.value=null}
function reset(){file.value=null;preview.value='';result.value=null;error.value='';state.value='idle';if(input.value)input.value.value=''}
function boxStyle(box:number[]|null){if(!box)return {};const[ymin,xmin,ymax,xmax]=box;return{top:`${ymin/10}%`,left:`${xmin/10}%`,width:`${(xmax-xmin)/10}%`,height:`${(ymax-ymin)/10}%`}}
async function analyze(){if(!file.value){error.value='Add a photo before analyzing.';state.value='error';return}state.value='analyzing';error.value='';const body=new FormData();body.append('image',file.value);body.append('place_type',placeType.value);body.append('perspective',perspective.value);body.append('location_description',`${location.value ? 'Location: '+location.value+'. ' : ''}${description.value}`);try{const r=await fetch(`${import.meta.env.VITE_API_BASE_URL||(window.location.hostname==='localhost'?'http://localhost:8000':'')}/api/audit`,{method:'POST',body});const p=await r.json().catch(()=>null);if(!r.ok)throw new Error(p?.detail||'Analysis failed. Please try again.');result.value=p;state.value='success';saveAudit(p);setTimeout(()=>document.getElementById('results')?.scrollIntoView({behavior:'smooth'}),50)}catch(e){error.value=e instanceof Error?e.message:'Analysis failed. Please retry.';state.value='error'}}
function saveAudit(a:Audit){caseId.value=`B2A-${new Date().toISOString().slice(0,10).replaceAll('-','')}-${Math.random().toString(36).slice(2,6).toUpperCase()}`;const item={id:Date.now(),createdAt:new Date().toLocaleString(),location:location.value||'Untitled location',summary:a.summary,status:a.status,result:a,preview:previewData.value};history.value=[item,...history.value].slice(0,10);localStorage.setItem('barrier2action-history',JSON.stringify(history.value))}
function saveComplaint(){localStorage.setItem('barrier2action-complaint-ref',complaintRef.value);localStorage.setItem('barrier2action-complaint-status',complaintStatus.value)}
function loadAudit(item:SavedAudit){result.value=item.result;location.value=item.location;preview.value=item.preview||'';previewData.value=item.preview||'';state.value='success';setTimeout(()=>document.getElementById('results')?.scrollIntoView({behavior:'smooth'}),50)}
function downloadReport(){if(!result.value)return;const text=`Barrier2Action audit\nLocation: ${location.value||'Not provided'}\nOwner: ${owner.value}\n\n${result.value.report_text}\n\nVisitor guidance: ${result.value.visitor_guidance}\n\nManager actions:\n-${result.value.manager_actions.join('\n-')}\n\nDisclaimer: Visual screening only; verify on site.`;const blob=new Blob([text],{type:'text/plain'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='barrier2action-report.txt';a.click();URL.revokeObjectURL(url)}
</script>
<template>
<div class="app-shell" :class="{'theme-dark':dark,'theme-light':!dark,'font-opendyslexic':readingFont==='opendyslexic','font-atkinson':readingFont==='atkinson','high-contrast':highContrast,'reduce-motion':reduceMotion}" :style="{'--user-text-scale':textScale}">
<header class="topbar"><div class="brand"><span class="brand-mark">↗</span><span>Barrier<span class="brand-accent">2</span>Action</span></div><div class="topbar-tools"><span class="beta">AI accessibility screening</span><button class="theme-toggle" @click="toggleTheme" type="button" :aria-label="dark?'Switch to light mode':'Switch to dark mode'">{{ dark?'☀':'☾' }} <span>{{dark?'Light':'Dark'}}</span></button></div></header>
<main><button class="accessibility-trigger" type="button" @click="toolbarOpen=!toolbarOpen" :aria-expanded="toolbarOpen">♿ Accessibility</button><section v-if="toolbarOpen" class="accessibility-toolbar card" aria-label="Reading preferences"><div><b>Reading preferences</b><p>Customize the interface for your needs.</p></div><label>Font<select :value="readingFont" @change="setReadingFont(($event.target as HTMLSelectElement).value)"><option value="default">Default</option><option value="opendyslexic">OpenDyslexic</option><option value="atkinson">Atkinson Hyperlegible</option></select></label><div class="font-size-control"><span>Text size</span><button type="button" @click="setScale(Math.max(.9,textScale-.1))">A−</button><button type="button" @click="setScale(1)">A</button><button type="button" @click="setScale(Math.min(1.3,textScale+.1))">A+</button></div><label class="check-control"><input type="checkbox" :checked="highContrast" @change="toggleContrast"> High contrast</label><label class="check-control"><input type="checkbox" :checked="reduceMotion" @change="toggleMotion"> Reduce motion</label><div class="toolbar-actions"><button type="button" @click="readReport">▶ Read report aloud</button><button type="button" @click="stopReading">■ Stop reading</button></div></section>
<section class="hero"><p class="eyebrow">SEE THE BARRIER. START THE CHANGE.</p><h1>Turn one photo<br><em>into accessible action.</em></h1><p class="hero-copy">A calm, practical first look at the built environment — powered by visual AI, grounded in what people can actually see.</p><div class="steps"><span><b></b>Capture</span><i>→</i><span><b></b>Context</span><i>→</i><span><b></b>Act</span></div></section>
<section class="workspace card"><div class="section-heading"><div><span class="step-number">01</span><h2>Show us the space</h2><p>Upload a clear photo of an entrance, route, or public area.</p></div><span class="hint">JPG · PNG · WEBP · AVIF</span></div><div class="dropzone" :class="{filled:preview}" @click="input?.click()" @keydown.enter="input?.click()" tabindex="0" role="button"><input ref="input" type="file" accept="image/jpeg,image/png,image/webp,image/avif" @change="chooseFile" hidden><template v-if="preview"><img :src="preview" alt="Selected accessibility audit photo"><button class="remove" type="button" @click.stop="reset">×</button></template><template v-else><div class="upload-icon">↑</div><strong>Drop a photo here or <u>browse</u></strong><span>One image at a time · maximum 8 MB</span></template></div>
<div class="section-heading context-head"><div><span class="step-number">02</span><h2>Add a little context</h2><p>Make this report useful to the person who can act on it.</p></div></div><div class="field-grid"><label>Place type<select v-model="placeType"><option value="campus">Campus / education</option><option value="shop">Shop / venue</option><option value="hospital">Healthcare</option><option value="transit">Transit</option><option value="office">Office</option><option value="street">Street / public realm</option><option value="other">Other</option></select></label><label>Perspective<select v-model="perspective"><option value="general">General access</option><option value="wheelchair">Wheelchair user</option><option value="low_vision">Low vision</option><option value="elderly">Older adult</option><option value="stroller">Stroller / caregiver</option></select></label></div><div class="field-grid"><label>Location or area <span class="optional">Optional</span><input v-model="location" placeholder="e.g. North library entrance"></label><label>Action owner<select v-model="owner"><option>Facilities</option><option>Campus operations</option><option>Venue manager</option><option>Safety team</option><option>Unassigned</option></select></label></div><label class="field-label">Anything else we should know? <span class="optional">Optional</span><textarea v-model="description" maxlength="300" placeholder="For example: This is the only entrance to the library."></textarea></label><div v-if="error" class="error" role="alert">! {{ error }}</div><button class="primary" :disabled="state==='analyzing'" @click="analyze"><span v-if="state==='analyzing'" class="spinner"></span>{{ state==='analyzing'?'Reading the space…':'Analyze this space  ↗' }}</button><p class="privacy">Your image is processed for this analysis and not saved by Barrier2Action.</p></section>
<section v-if="history.length" class="history"><div class="section-heading"><div><span class="eyebrow">LOCAL WORKSPACE</span><h2>Recent audits</h2></div><span class="hint">Stored in this browser</span></div><div class="history-list"><button v-for="item in history" :key="item.id" class="history-item" @click="loadAudit(item)"><span class="history-dot" :class="item.status"></span><span><b>{{item.location}}</b><small>{{item.createdAt}}</small></span><strong>→</strong></button></div></section>
<section v-if="result" id="results" class="results"><div class="results-title"><div><p class="eyebrow">YOUR ACTION REPORT</p><h2>What we can see</h2><p class="report-meta">{{location||'Location not provided'}} · Assigned to {{owner}}</p></div><div class="result-actions"><button class="secondary" @click="downloadReport">↓ Download report</button><span class="status" :class="statusClass">{{statusLabel}}</span></div></div>
<div class="impact-grid"><div class="impact-card"><strong>{{result.barriers.length}}</strong><span>Visible barriers</span></div><div class="impact-card"><strong>{{highCount}}</strong><span>High priority</span></div><div class="impact-card"><strong>{{affectedCount}}</strong><span>User groups affected</span></div><div class="impact-card"><strong>{{Math.round(result.overall_confidence*100)}}%</strong><span>Visual confidence</span></div></div>
<div class="evidence-layout"><div class="evidence-image card"><div class="image-stage"><img :src="preview" alt="Audited space with evidence markers"><span v-for="(b,i) in result.barriers.filter(item => item.box_2d)" :key="i" class="evidence-box" :style="boxStyle(b.box_2d)">{{i+1}}</span></div><p>Evidence markers are approximate visual cues, not measurements.</p></div><div class="summary card"><span class="small-label">OBSERVATION</span><p>{{result.summary}}</p><div class="confidence"><span>Visual confidence</span><strong>{{Math.round(result.overall_confidence*100)}}%</strong><div><i :style="{width:(result.overall_confidence*100)+'%'}"></i></div></div></div></div>
<div class="barriers"><div class="results-title"><h3>{{result.barriers.length?'Priority observations':'No visible barriers found'}}</h3><span>{{result.barriers.length}} found</span></div><article v-for="(b,i) in result.barriers" :key="b.label" class="barrier card" :class="{open:expanded===i}"><button class="barrier-header" @click="expanded=expanded===i?null:i"><span class="number">{{i+1}}</span><span><span class="urgency" :class="b.urgency">{{b.urgency}} priority</span><strong>{{b.label}}</strong><small>{{Math.round(b.confidence*100)}}% confidence · {{b.affected_users.length}} groups affected</small></span><b>{{expanded===i?'−':'+'}}</b></button><div v-if="expanded===i" class="barrier-body"><p>{{b.visible_evidence}}</p><div class="affected"><span>Affects</span><b v-for="person in b.affected_users" :key="person">{{person}}</b></div><div class="actions"><div><small>NOW</small><p>{{b.immediate_guidance}}</p></div><div><small>LOW-COST STEP</small><p>{{b.low_cost_action}}</p></div><div><small>LONGER-TERM CHANGE</small><p>{{b.structural_action}}</p></div></div></div></article></div>
<div v-if="result.cannot_confirm.length" class="uncertainty card"><span class="small-label">WHAT THIS PHOTO CANNOT CONFIRM</span><ul><li v-for="item in result.cannot_confirm" :key="item">{{item}}</li></ul></div><div class="tabs card"><div class="tab-buttons"><button :class="{active:activeTab==='visitor'}" @click="activeTab='visitor'">Visitor guidance</button><button :class="{active:activeTab==='manager'}" @click="activeTab='manager'">Facility actions</button><button :class="{active:activeTab==='report'}" @click="activeTab='report'">Ready-to-send report</button></div><div v-if="activeTab==='visitor'"><p>{{result.visitor_guidance}}</p></div><div v-if="activeTab==='manager'"><ul><li v-for="item in result.manager_actions" :key="item">{{item}}</li></ul></div><div v-if="activeTab==='report'"><p class="report">{{result.report_text}}</p><button class="secondary" @click="downloadReport">Download text report</button></div></div></section>
<section v-if="result" class="action-center card"><div><p class="eyebrow">CLOSE THE LOOP</p><h3>Turn this finding into action</h3><p>Case <b>{{caseId}}</b> · Route this issue to <b>{{actionRoute.name}}</b>.</p></div><a v-if="actionRoute.url" class="secondary" :href="actionRoute.url" target="_blank" rel="noreferrer">Open official channel ↗</a></section><section v-if="result && (result.evidence_quality==='low'||result.requested_photos?.length)" class="follow-up card"><p class="eyebrow">SMART FOLLOW-UP</p><h3>What we need to see next</h3><p class="follow-copy">This view may not be enough to verify access. Take these photos to strengthen the case:</p><ul><li v-for="photo in result.requested_photos" :key="photo">{{photo}}</li></ul></section><section v-if="result" class="tracking card"><div><p class="eyebrow">REPORT TRACKING</p><h3>Have a reference number?</h3><p>Save the reference from the official channel so you can follow up later.</p></div><input v-model="complaintRef" placeholder="e.g. PGRS-12345"><select v-model="complaintStatus"><option>Not submitted</option><option>Submitted</option><option>In progress</option><option>Resolved</option></select><button class="secondary" @click="saveComplaint">Save status</button></section></main><footer>Barrier2Action is a visual screening assistant, not a professional accessibility certification or legal compliance assessment.</footer></div>
</template>
